apiVersion: v1
kind: Pod
metadata:
  name: time
  namespace: garden
  labels:
    app: time
spec:
  containers:
    - name: time
      image: ghcr.io/choste/time@sha256:df4a23205bb071a07699c9c44bd3fb0b9a87cba97e9397932ba4a8261222fd22
      ports:
        - containerPort: 3000
