apiVersion: v1
kind: Pod
metadata:
  name: time
  namespace: garden
  labels:
    app: time
spec:
  containers:
    - name: time
      image: ghcr.io/choste/time@sha256:20e086dcf2426b0304004d064cd2fd10dbc8aae5d086fe913e302b1547a326be
      ports:
        - containerPort: 3000
