apiVersion: v1
kind: Pod
metadata:
  name: time
  namespace: garden
  labels:
    app: time
spec:
  containers:
    - name: time
      image: ghcr.io/choste/time:main
      ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: time-service
  namespace: garden
spec:
  selector:
    app: time
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
